Repository wantPlant/wantPlant_BE, pull requests merged in 2024-01, with the labels that each got.

#5 FEAT : 수정사항 반영
  .idea/.gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/wantPlant.main.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/wantPlant_BE.iml
  wantPlant/.gitignore
  wantPlant/build.gradle
  wantPlant/src/main/java/umc/wantPlant/apipayload/ApiResponse.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/code/BaseCode.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/code/BaseErrorCode.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/code/ErrorReasonDTO.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/code/ReasonDTO.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/code/status/ErrorStatus.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/code/status/SuccessStatus.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/exceptions/ExceptionAdvice.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/exceptions/GeneralException.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/exceptions/handler/GardenHandler.java
  wantPlant/src/main/java/umc/wantPlant/config/SwaggerConfig.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandService.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryService.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/Garden.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/enums/GardenCategories.java
  wantPlant/src/main/java/umc/wantPlant/garden/repository/GardenRepository.java
  wantPlant/src/main/java/umc/wantPlant/garden/ui/GardenController.java
Labels: :sparkles: feature

#7 ✨ FEAT: 정원삭제, 수정 , 조회 기능 구현완료
  .idea/.gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/wantPlant.main.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/wantPlant_BE.iml
  wantPlant/.gitignore
  wantPlant/build.gradle
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandService.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryService.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/Garden.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/repository/GardenRepository.java
  wantPlant/src/main/java/umc/wantPlant/garden/ui/GardenController.java
Labels: :sparkles: feature

#11 ✨ Feat : pot domian, dto
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotCommandService.java
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotQueryService.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/Pot.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/dto/PotRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/dto/PotResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/enums/PotTagColor.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/enums/PotType.java
  wantPlant/src/main/java/umc/wantPlant/pot/repository/PotRepository.java
  wantPlant/src/main/java/umc/wantPlant/pot/ui/PotController.java
Labels: :sparkles: feature

#17 FEAT: todo crud
  wantPlant/src/main/java/umc/wantPlant/todo/application/TodoService.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/Todo.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/dto/TodoRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/dto/TodoResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/todo/repository/TodoRepository.java
  wantPlant/src/main/java/umc/wantPlant/todo/ui/TodoController.java
Labels: :sparkles: feature

#20 feat: todo crud구현
  wantPlant/src/main/java/umc/wantPlant/todo/application/TodoService.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/Todo.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/dto/TodoRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/dto/TodoResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/todo/ui/TodoController.java
Labels: :sparkles: feature

#23 ♻️ REFACTOR : 정원 조회 API에 Pot리스트 추가하기
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandService.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/Garden.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/repository/GardenRepository.java
  wantPlant/src/main/java/umc/wantPlant/garden/ui/GardenController.java
Labels: :recycle: refactor

#25 FEAT: pot 추가 기능
  wantPlant/src/main/java/umc/wantPlant/goal/application/GoalCommandServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotCommandService.java
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotCommandServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotQueryService.java
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotQueryServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/Pot.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/dto/PotRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/dto/PotResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/enums/PotType.java
  wantPlant/src/main/java/umc/wantPlant/pot/repository/PotRepository.java
  wantPlant/src/main/java/umc/wantPlant/pot/ui/PotController.java
  wantPlant/src/main/java/umc/wantPlant/todo/application/TodoService.java
  wantPlant/src/main/java/umc/wantPlant/todo/repository/TodoRepository.java
Labels: :sparkles: feature

#27 feat: 파일 설정 및 업로드 기능 구현
  wantPlant/build.gradle
  wantPlant/src/main/java/umc/wantPlant/WantPlantApplication.java
  wantPlant/src/main/java/umc/wantPlant/file/config/AwsConfig.java
  wantPlant/src/main/java/umc/wantPlant/file/controller/FileController.java
  wantPlant/src/main/java/umc/wantPlant/file/domain/S3File.java
  wantPlant/src/main/java/umc/wantPlant/file/domain/S3FileDto.java
  wantPlant/src/main/java/umc/wantPlant/file/service/AmazonS3Service.java
  wantPlant/src/main/java/umc/wantPlant/tag/domain/dto/request/TagRequestDto.java
  wantPlant/src/test/java/umc/wantPlant/tag/application/TagServiceTest.java
Labels: :sparkles: feat
