Repository wantPlant/wantPlant_BE, pull requests merged in 2024-02, with the labels that each got.

#33 ✨ FEAT: 정원 검증로직 , 전체조회 API 추가
  wantPlant/src/main/java/umc/wantPlant/apipayload/code/status/ErrorStatus.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/exceptions/ExceptionAdvice.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/exceptions/handler/GardenCategoryHandler.java
  wantPlant/src/main/java/umc/wantPlant/file/config/AwsConfig.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandService.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryService.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/Garden.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/repository/GardenRepository.java
  wantPlant/src/main/java/umc/wantPlant/garden/ui/GardenController.java
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotCommandService.java
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotCommandServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotQueryServiceImpl.java
Labels: :sparkles: feature

#38 Feat/32 oauth login
  wantPlant/build.gradle
  wantPlant/src/main/java/umc/wantPlant/apipayload/code/status/ErrorStatus.java
  wantPlant/src/main/java/umc/wantPlant/config/SwaggerConfig.java
  wantPlant/src/main/java/umc/wantPlant/config/security/SecurityConfig.java
  wantPlant/src/main/java/umc/wantPlant/config/security/jwt/JwtAuthenticationFilter.java
  wantPlant/src/main/java/umc/wantPlant/config/security/jwt/JwtExceptionFilter.java
  wantPlant/src/main/java/umc/wantPlant/config/security/jwt/JwtTokenProvider.java
  wantPlant/src/main/java/umc/wantPlant/config/security/jwt/TokenInfo.java
  wantPlant/src/main/java/umc/wantPlant/config/security/oauth/PrincipalDetails.java
  wantPlant/src/main/java/umc/wantPlant/config/security/oauth/PrincipalDetailsService.java
  wantPlant/src/main/java/umc/wantPlant/member/application/AuthService.java
  wantPlant/src/main/java/umc/wantPlant/member/application/RefreshTokenService.java
  wantPlant/src/main/java/umc/wantPlant/member/client/KakaoMemberClient.java
  wantPlant/src/main/java/umc/wantPlant/member/domain/Member.java
  wantPlant/src/main/java/umc/wantPlant/member/domain/RefreshToken.java
  wantPlant/src/main/java/umc/wantPlant/member/domain/dto/request/MemberGenerateTokenRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/member/domain/dto/response/MemberGenerateTokenResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/member/domain/dto/response/MemberLoginResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/member/repository/MemberRepository.java
  wantPlant/src/main/java/umc/wantPlant/member/repository/RefreshTokenRepository.java
  wantPlant/src/main/java/umc/wantPlant/member/ui/AuthController.java
Labels: :sparkles: feature

#40 FEAT: tag 삭제 성공시 성공 메시지 구현
  wantPlant/src/main/java/umc/wantPlant/tag/ui/TagController.java
Labels: :sparkles: feature

#41 Feat:ApiResponse통일 및 투두시간 날짜분리
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/wantPlant.main.iml
  .idea/vcs.xml
  .idea/wantPlant_BE.iml
  wantPlant/src/main/java/umc/wantPlant/goal/application/GoalQueryService.java
  wantPlant/src/main/java/umc/wantPlant/goal/application/GoalQueryServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/goal/domain/dto/GoalRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/goal/domain/dto/GoalResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/dto/PotRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/todo/application/TodoService.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/Todo.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/dto/TodoRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/dto/TodoResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/todo/repository/TodoRepository.java
  wantPlant/src/main/java/umc/wantPlant/todo/ui/TodoController.java
Labels: :sparkles: feature

#45 FEAT: add WebMvcConfig
  wantPlant/src/main/java/umc/wantPlant/config/WebMvcConfig.java
Labels: :sparkles: feature

#47 Refactor: Config 파일 병합
  wantPlant/src/main/java/umc/wantPlant/config/WebConfig.java
  wantPlant/src/main/java/umc/wantPlant/config/WebMvcConfig.java
Labels: :recycle: refactor

#53 REFACTOR: cors 인증 헤더 관련설정 추가
  wantPlant/src/main/java/umc/wantPlant/config/security/SecurityConfig.java
Labels: :recycle: refactor

#50 FEAT : 날짜와 화분 별 todos, goals 조회 API
  wantPlant/src/main/java/umc/wantPlant/goal/application/GoalQueryService.java
  wantPlant/src/main/java/umc/wantPlant/goal/application/GoalQueryServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/goal/domain/dto/GoalResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/goal/repository/GoalRepository.java
  wantPlant/src/main/java/umc/wantPlant/goal/ui/GoalController.java
  wantPlant/src/main/java/umc/wantPlant/todo/application/TodoService.java
  wantPlant/src/main/java/umc/wantPlant/todo/repository/TodoRepository.java
Labels: :sparkles: feature

#56 FEAT: 로그아웃 API 구현, 리팩토링
  wantPlant/src/main/java/umc/wantPlant/config/security/oauth/CurrentMember.java
  wantPlant/src/main/java/umc/wantPlant/member/application/AuthService.java
  wantPlant/src/main/java/umc/wantPlant/member/domain/dto/response/MemberLoginResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/member/ui/AuthController.java
  wantPlant/src/main/java/umc/wantPlant/member/ui/MemberController.java
Labels: :sparkles: feature, :recycle: refactor

#59 태그 에러 핸들러 추가, 내 모든 정원 조회 오류 수정
  wantPlant/src/main/java/umc/wantPlant/apipayload/code/status/ErrorStatus.java
  wantPlant/src/main/java/umc/wantPlant/apipayload/exceptions/handler/TagHandler.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryService.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/ui/GardenController.java
  wantPlant/src/main/java/umc/wantPlant/garden/ui/GardenControllerTemp.java
  wantPlant/src/main/java/umc/wantPlant/tag/application/TagService.java
Labels: :bug: hotfix

#60 정원 삭제 버그 수정
  wantPlant/src/main/java/umc/wantPlant/completedPot/domain/CompletedPot.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/Garden.java
  wantPlant/src/main/java/umc/wantPlant/garden/repository/GardenRepository.java
  wantPlant/src/main/java/umc/wantPlant/garden/ui/GardenControllerTemp.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/Pot.java
  wantPlant/src/main/java/umc/wantPlant/todo/domain/Todo.java
Labels: :bug: hotfix

#57 FEAT : 조회 시 화분 태그 컬러 field 추가
  wantPlant/src/main/java/umc/wantPlant/pot/application/PotQueryServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/pot/domain/dto/PotResponseDTO.java
Labels: :sparkles: feature

#62 [REFACTOR] 정원 리팩토링 및 테스트 일부 추가
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandService.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenCommandServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryService.java
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryServiceImpl.java
  wantPlant/src/main/java/umc/wantPlant/garden/converter/GardenConverter.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenRequestDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/domain/dto/GardenResponseDTO.java
  wantPlant/src/main/java/umc/wantPlant/garden/repository/GardenRepository.java
  wantPlant/src/main/java/umc/wantPlant/garden/ui/GardenController.java
  wantPlant/src/main/java/umc/wantPlant/garden/ui/GardenControllerTemp.java
  wantPlant/src/test/java/umc/wantPlant/garden/application/GardenServiceTest.java
Labels: :recycle: refactor

#66 :bug: HOTFIX: 정원 삭제 에러해결
  wantPlant/src/main/java/umc/wantPlant/goal/domain/Goal.java
Labels: :bug: hotfix

#68 ♻️ REFACTOR: 정원 페이지 사이즈 3으로 수정
  wantPlant/src/main/java/umc/wantPlant/garden/application/GardenQueryServiceImpl.java
Labels: :recycle: refactor

#71 HOTFIX : pot proceed non-negative 처리
  wantPlant/src/main/java/umc/wantPlant/pot/domain/Pot.java
Labels: :bug: hotfix
